[project]
name = "companias"
version = "1.0.0"
authors = [
  { name="", email="" },
]
description = "Proyecto de ejemplo de Companias"
readme = "README.md"
requires-python = ">=3.10"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = [
  ".", "src",
]